easy_admin:
    entities:

        Productor:
            class: App\Entity\Productor
            list:
                title: 'Les producteurs'
                help: 'Ajouter, modifier ou supprimer un producteur'
                actions:
                    - { name: 'new', label: 'Ajouter un producteur'}
                    - { name: 'edit', icon: 'pencil' }
                    - { name: 'delete', icon: 'trash-alt'}
                batch_actions: ['delete']
                fields:
                    - { property: 'name', label: 'Nom' }
                    - { property: 'filename', label: 'Image', type: 'image', base_path: 'img/producteurs/' }
                    - { property: 'image_description', label: "Description de l'image" }
                    - { property: 'delivery', label: "Livraison"}
                    - label
            new:
                title: 'Créer un producteur'
                fields:
                    - {type: 'group', columns: 6, label: 'Informations générales', icon: 'info-circle'}
                    - { property: 'name', label: 'Nom' }
                    - { property: 'delivery', label: "Livraison"}
                    - label
                    - {type: 'group', columns: 4, label: 'Contrat', icon: 'file-contract'}
                    - { property: 'contracts', label: 'Contrats', type: 'embedded_list' }
                    - {type: 'group', columns: 6, label: 'Photo', icon: 'image'}
                    - { property: 'filename', label: 'Image', type: 'file', base_path: 'img/producteurs/'}
                    - { property: 'image_description', label: "Description de l'image" }
            edit:
                title: 'Modifier le producteur'
                fields:
                    - {type: 'group', columns: 4, label: 'Informations générales', icon: 'info-circle'}
                    - { property: 'name', label: 'Nom' }
                    - { property: 'delivery', label: "Livraison"}
                    - label
                    - {type: 'group', columns: 4, label: 'Contrat', icon: 'file-contract'}
                    - { property: 'contracts', label: 'Contrats', type: 'embedded_list' }
                    - {type: 'group', columns: 4, label: 'Photo', icon: 'image'}
                    - { property: 'imageFile', label: 'Image', type: 'file', base_path: 'img/producteurs/' }
                    - { property: 'image_description', label: "Description de l'image" }
        Contract:
            class: App\Entity\Contract
            list:
                title: 'Les contrats'
                actions:
                    - { name: 'new', label: 'Ajouter un contrat'}
                    - { name: 'edit', icon: 'pencil' }
                    - { name: 'delete', icon: 'trash-alt'}
                fields:
                    - { property: 'productor', label: 'Producteur'}
                    - { property: 'name', label: 'Nom' }
                    - { property: 'fileName', label: 'Fichier PDF', type: 'file', base_path: '/doc/contrats', filename: 'Voir le contrat (PDF)' }
            help: 'Ajouter, modifier ou supprimer un contrat'
            new:
                title: 'Ajouter un contrat'
                fields:
                    - { property: 'productor', label: 'Producteur'}
                    - { property: 'name', label: 'Nom' }
                    - { property: 'pdfFile', label: 'Fichier PDF', type: 'file', base_path: '/doc/contrats' }
            edit:
                title: 'Modifier un contrat'
                fields:
                    - { property: 'productor', label: 'Producteur'}
                    - { property: 'name', label: 'Nom' }
                    - { property: 'pdfFile', label: 'Fichier PDF', type: 'file'}



        GalleryImage:
            class: App\Entity\GalleryImage
            list:
                title: 'Galerie'
                help: 'Ajouter, modifier ou supprimer une image de la galerie'
                actions:
                    - { name: 'new', label: 'Ajouter une image'}
                    - { name: 'edit', icon: 'pencil' }
                    - { name: 'delete', icon: 'trash-alt'}
                batch_actions: ['delete']
                fields:
                    - { property: 'image_file_name', label: 'Image', type: 'image', base_path: 'img/gallery/' }
                    - { property: 'description', label: "Description de l'image" }


        News:
            class: App\Entity\News
            list:
                title: 'Actualité'
                help: "Ajouter, modifier ou supprimer le contenu de la page d'accueil"
                actions:
                    - { name: 'new', label: 'Ajouter du contenu'}
                    - { name: 'edit', icon: 'pencil' }
                    - { name: 'delete', icon: 'trash-alt'}
                fields:
                    - { property: 'content', label: 'Contenu' }
            new:
                title: 'Ajouter du contenu'
                fields:
                    - { property: 'content', label: 'Contenu' }
            edit:
                title: 'Modifier le contenu'
                fields:
                    - { property: 'content', label: 'Contenu' }

        User:
            class: App\Entity\User
            list:
                title: 'Utilisateur'
                help: 'Ajouter, modifier ou supprimer un utilisateur'
                action:
                    - { name: 'new', label: 'Ajouter un utilisateur'}
                    - { name: 'edit', icon: 'pencil' }
                    - { name: 'delete', icon: 'trash-alt'}
                fields:
                    - { property: 'last_name', label: 'Nom' }
                    - { property: 'first_name', label: 'Prénom' }
                    - { property: 'email', label: 'Email' }
                    - { property: 'address', label: 'Adresse' }
                    - { property: 'zip', label: 'Code postal' }
                    - { property: 'city', label: 'Ville' }
                    - { property: 'phone', label: 'Téléphone' }
                    - { property: 'role', label: 'Rôle'}
            new:
                title: 'Créer un utilisateur'
                fields:
                    - {type: 'group', columns: 6, label: 'Détails', icon: 'user'}
                    - { property: 'last_name', label: 'Nom' }
                    - { property: 'first_name', label: 'Prénom' }
                    - { property: 'email', label: 'Email' }
                    - { property: 'role', label: 'Rôle'}
                    - {type: 'group', columns: 6, label: 'Coordonnées', icon: 'phone'}
                    - { property: 'address', label: 'Adresse' }
                    - { property: 'zip', label: 'Code postal' }
                    - { property: 'city', label: 'Ville' }
                    - { property: 'phone', label: 'Téléphone' }
            edit:
                title: 'Modifier un utilisateur'
                fields:
                    - {type: 'group', columns: 6, label: 'Détails', icon: 'user'}
                    - { property: 'last_name', label: 'Nom' }
                    - { property: 'first_name', label: 'Prénom' }
                    - { property: 'email', label: 'Email' }
                    - { property: 'role', label: 'Rôle'}
                    - {type: 'group', columns: 6, label: 'Coordonnées', icon: 'phone'}
                    - { property: 'address', label: 'Adresse' }
                    - { property: 'zip', label: 'Code postal' }
                    - { property: 'city', label: 'Ville' }
                    - { property: 'phone', label: 'Téléphone' }

    site_name: '<img src="/img/logo.svg"/>'

    design:
        menu:
            - {entity: 'Productor', label: 'Producteurs', icon: 'tractor'}
            - {entity: 'Contract', label: 'Contrats', icon: 'file-contract'}
            - {entity: 'GalleryImage', label: 'Galerie', icon: 'camera'}
            - {entity: 'News', label: 'Actualité', icon: 'newspaper'}
            - {entity: 'User', label: 'Utilisateurs', icon: 'user'}
            - { label: 'Site', url: 'http://retournamap.local/', icon: 'home'}
        assets:
            favicon: 'img/logopetit.png'
            css:
                - 'style/admin.css'
        brand_color: '#f29400'

    user:
        name_property_path: 'username'
        avatar_property_path: 'gravatar'
