vich_uploader:
    db_driver: orm

    mappings:
        producteur_image:
            uri_prefix: /img/producteurs
            upload_destination: '%kernel.project_dir%/public/img/producteurs'

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
